package org.mustangproject.validator;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.xmlunit.assertj.XmlAssert.assertThat;

/**
 * Validates the XML and PDF generated by the library's HierarchicalPositionsTest
 * using Mustang's own ZUGFeRDValidator (XSD + Schematron).
 * <p>
 * This test expects the library module to have been built and tested first,
 * so that the output files exist in {@code ../library/target/}.
 */
public class HierarchicalXMLValidationTest extends ResourceCase {

    public void testHierarchicalTrainTicketXMLValid() throws Exception {
        File xmlFile = new File("../library/target/testout-ZF2HierarchicalTrainTicket.xml");
        if (!xmlFile.exists()) {
            System.out.println("SKIP: " + xmlFile.getAbsolutePath() + " not found. Run library tests first.");
            return;
        }

        ZUGFeRDValidator zfv = new ZUGFeRDValidator();
        String res = zfv.validate(xmlFile.getAbsolutePath());

        // Write result to file for inspection
        Files.write(Paths.get("target/testout-ZF2HierarchicalTrainTicket-validation.xml"),
                res.getBytes(StandardCharsets.UTF_8));

        // Print to stderr so it shows in surefire output
        System.err.println(res);

        // Must have zero errors
        assertThat(res).valueByXPath("count(//error)")
            .asInt()
            .isEqualTo(0);

        // Must have zero warnings (hierarchy mismatch warnings should not occur)
        assertThat(res).valueByXPath("count(//warning)")
            .asInt()
            .isEqualTo(0);

        assertThat(res).valueByXPath("/validation/summary/@status")
            .asString()
            .isEqualTo("valid");

        assertThat(res).valueByXPath("/validation/xml/summary/@status")
            .asString()
            .isEqualTo("valid");
    }
}
